image: registry.gitlab.com/lilypond-projects/lilylib/lilypond:2.19.83

variables:
    GIT_SUBMODULE_STRATEGY: normal

build:
    script:
        - make
    artifacts:
        paths:
            - "*.pdf"
