name: Build
on: push

jobs:
  build:
    name: Build Scores
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Compile Files
        uses: docker://codello/lilypond:shell
        with:
          entrypoint: make
          args: ci
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Furientanz
          path: build
